# Generated by Django 3.0.4 on 2020-03-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
