# Generated by Django 3.0.4 on 2020-03-16 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200316_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
